/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "I2C.h"
#include "I2C_PINS.h"
#include "I2C_PVT.h"
#include "I2C_EZI2C.h"
#include "I2C_EZI2C_PVT.h"
#include "I2C_BOOT.h"
#include "Input_1_Int.h"
#include "Input_0_Int.h"
#include "Input_Pin_1.h"
#include "Input_Pin_1_aliases.h"
#include "Input_Pin_0.h"
#include "Input_Pin_0_aliases.h"
#include "Output_Pin_0.h"
#include "Output_Pin_0_aliases.h"
#include "Output_Pin_1.h"
#include "Output_Pin_1_aliases.h"
#include "Output_Pin_2.h"
#include "Output_Pin_2_aliases.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

