/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM_3.h"
#include "PWM_2.h"
#include "PWM_1.h"
#include "Led_A.h"
#include "Led_A_aliases.h"
#include "Led_B.h"
#include "Led_B_aliases.h"
#include "Led_C.h"
#include "Led_C_aliases.h"
#include "Led_D.h"
#include "Led_D_aliases.h"
#include "CapSense.h"
#include "CapSense_CSHL.h"
#include "CapSense_TunerHelper.h"
#include "CapSense_SMS.h"
#include "CapSense_PVT.h"
#include "CapSense_IP.h"
#include "PWM_0.h"
#include "Clock_1MHz_1.h"
#include "CapSense_SampleClk.h"
#include "CapSense_Sns_aliases.h"
#include "CapSense_SenseClk.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

