/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Pin_Green.h"
#include "Pin_Green_aliases.h"
#include "Pin_Red.h"
#include "Pin_Red_aliases.h"
#include "Pin_Blue.h"
#include "Pin_Blue_aliases.h"
#include "Pin_SW2.h"
#include "Pin_SW2_aliases.h"
#include "Clock_1.h"
#include "PWM.h"
#include "I2C.h"
#include "I2C_PINS.h"
#include "I2C_PVT.h"
#include "I2C_EZI2C.h"
#include "I2C_EZI2C_PVT.h"
#include "I2C_BOOT.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

